# Generated by Django 4.2.29 on 2026-03-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('ASSET', 'Thiết bị'), ('WO', 'Work Order'), ('INCIDENT', 'Sự cố'), ('HANDOVER', 'Bàn giao'), ('COMPLIANCE', 'Kiểm định/Hiệu chuẩn'), ('CHECKLIST_ITEM', 'Mục checklist'), ('OTHER', 'Khác')], max_length=30)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Nhóm tài liệu',
                'verbose_name_plural': 'Nhóm tài liệu',
                'db_table': 'document_groups',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('MANUAL', 'Hướng dẫn sử dụng'), ('SOP', 'Quy trình'), ('CERTIFICATE', 'Chứng chỉ'), ('REPORT', 'Báo cáo'), ('PHOTO', 'Ảnh'), ('VIDEO', 'Video'), ('HANDOVER_FORM', 'Biên bản bàn giao'), ('OTHER', 'Khác')], max_length=20)),
                ('file_name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.IntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents_app.documentgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'db_table': 'documents',
                'indexes': [models.Index(fields=['tenant', 'group', '-uploaded_at'], name='documents_tenant__900f38_idx')],
            },
        ),
    ]
