# Generated by Django 4.2.29 on 2026-03-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations_app.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Khoa/Phòng',
                'verbose_name_plural': 'Khoa/Phòng',
                'db_table': 'departments',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BRANCH', 'Chi nhánh'), ('BUILDING', 'Tòa nhà'), ('FLOOR', 'Tầng'), ('DEPARTMENT_AREA', 'Khu vực khoa'), ('ROOM', 'Phòng'), ('BED', 'Giường'), ('WAREHOUSE', 'Kho'), ('OTHER', 'Khác')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations_app.department')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations_app.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Vị trí',
                'verbose_name_plural': 'Vị trí',
                'db_table': 'locations',
                'indexes': [models.Index(fields=['tenant', 'parent'], name='locations_tenant__b34d4c_idx'), models.Index(fields=['tenant', 'type'], name='locations_tenant__71d97d_idx')],
            },
        ),
    ]
