# Generated by Django 4.2.29 on 2026-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=100, verbose_name='Mã thiết bị')),
                ('asset_name', models.CharField(max_length=300, verbose_name='Tên thiết bị')),
                ('asset_type', models.CharField(choices=[('MAIN', 'Thiết bị chính'), ('ACCESSORY', 'Phụ kiện'), ('TOOL', 'Dụng cụ')], default='MAIN', max_length=20, verbose_name='Loại')),
                ('serial_no', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('imei', models.CharField(blank=True, max_length=50, verbose_name='IMEI')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='Barcode/QR')),
                ('model_name_manual', models.CharField(blank=True, max_length=200, verbose_name='Model (nhập tay)')),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True, verbose_name='Năm sản xuất')),
                ('risk_class', models.CharField(blank=True, choices=[('', 'Không phân loại'), ('Class A', 'Class A'), ('Class B', 'Class B'), ('Class C', 'Class C'), ('Class D', 'Class D'), ('Class I', 'Class I'), ('Class IIa', 'Class IIa'), ('Class IIb', 'Class IIb'), ('Class III', 'Class III')], max_length=20, verbose_name='Risk Class')),
                ('criticality', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Nghiêm trọng')], default='MEDIUM', max_length=20, verbose_name='Mức độ ưu tiên')),
                ('is_portable', models.BooleanField(default=False, verbose_name='Thiết bị di động')),
                ('current_status', models.CharField(choices=[('IN_SERVICE', 'Đang sử dụng'), ('STANDBY', 'Dự phòng'), ('UNDER_MAINTENANCE', 'Đang bảo trì'), ('BREAKDOWN', 'Hỏng'), ('OUT_OF_SERVICE', 'Ngừng hoạt động'), ('DECOMMISSIONED', 'Đã thanh lý')], default='IN_SERVICE', max_length=30, verbose_name='Trạng thái')),
                ('commissioned_at', models.DateField(blank=True, null=True, verbose_name='Ngày đưa vào sử dụng')),
                ('installed_at', models.DateField(blank=True, null=True, verbose_name='Ngày lắp đặt')),
                ('purchase_at', models.DateField(blank=True, null=True, verbose_name='Ngày mua')),
                ('warranty_start_at', models.DateField(blank=True, null=True, verbose_name='Bảo hành từ')),
                ('warranty_end_at', models.DateField(blank=True, null=True, verbose_name='Bảo hành đến')),
                ('expected_eol_at', models.DateField(blank=True, null=True, verbose_name='Ngày hết vòng đời (EOL)')),
                ('useful_life_years', models.IntegerField(default=2, verbose_name='Vòng đời (năm)')),
                ('inspection_required', models.BooleanField(default=True, verbose_name='Yêu cầu kiểm định')),
                ('inspection_last_date', models.DateField(blank=True, null=True, verbose_name='Ngày kiểm định cuối')),
                ('inspection_expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn kiểm định')),
                ('pm_required', models.BooleanField(default=True, verbose_name='Yêu cầu PM')),
                ('pm_last_date', models.DateField(blank=True, null=True, verbose_name='Ngày PM cuối')),
                ('pm_next_due_date', models.DateField(blank=True, null=True, verbose_name='Ngày PM kế tiếp')),
                ('service_contract_id', models.CharField(blank=True, max_length=100, verbose_name='Mã hợp đồng dịch vụ')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Hết hạn hợp đồng')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Tòa nhà')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Tầng')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Phòng')),
                ('bed', models.CharField(blank=True, max_length=50, verbose_name='Giường')),
                ('ops_note', models.TextField(blank=True, verbose_name='Ghi chú vận hành')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Vô hiệu hóa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Thiết bị y tế',
                'verbose_name_plural': 'Thiết bị y tế',
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nhóm thiết bị',
                'verbose_name_plural': 'Nhóm thiết bị',
                'db_table': 'asset_categories',
            },
        ),
        migrations.CreateModel(
            name='AssetHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='COMPONENT', max_length=50)),
            ],
            options={
                'verbose_name': 'Phân cấp thiết bị',
                'verbose_name_plural': 'Phân cấp thiết bị',
                'db_table': 'asset_hierarchy',
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('model_code', models.CharField(blank=True, max_length=100)),
                ('spec_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Model thiết bị',
                'verbose_name_plural': 'Model thiết bị',
                'db_table': 'asset_models',
            },
        ),
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'db_table': 'asset_status_history',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nhà sản xuất',
                'verbose_name_plural': 'Nhà sản xuất',
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('service_hotline', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'db_table': 'vendors',
            },
        ),
    ]
