# Generated by Django 4.2.29 on 2026-03-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_app', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='assetstatushistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assets_app.asset'),
        ),
        migrations.AddField(
            model_name='assetstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetstatushistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='assets_app.manufacturer'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_models', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='assethierarchy',
            name='child_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='assets_app.asset'),
        ),
        migrations.AddField(
            model_name='assethierarchy',
            name='parent_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='assets_app.asset'),
        ),
        migrations.AddField(
            model_name='assethierarchy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets_app.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_app.assetcategory', verbose_name='Nhóm/Chủng loại'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='locations_app.location', verbose_name='Vị trí hiện tại'),
        ),
        migrations.AddField(
            model_name='asset',
            name='custodian_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_assets', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_app.manufacturer', verbose_name='Nhà sản xuất'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_app.assetmodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to='locations_app.department', verbose_name='Khoa/Phòng sở hữu'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets_app.vendor', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddIndex(
            model_name='assetstatushistory',
            index=models.Index(fields=['tenant', 'asset', '-changed_at'], name='asset_statu_tenant__25010d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assethierarchy',
            unique_together={('parent_asset', 'child_asset')},
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'asset_code'], name='assets_tenant__31b787_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'serial_no'], name='assets_tenant__b96d77_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'current_status'], name='assets_tenant__7995b6_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'owner_dept'], name='assets_tenant__e70b9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('tenant', 'asset_code')},
        ),
    ]
