# Generated by Django 4.2.29 on 2026-03-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='pm_interval_months',
            field=models.IntegerField(default=12, verbose_name='Chu kỳ PM (tháng)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Giá mua'),
        ),
    ]
