# Generated by Django 4.2.29 on 2026-03-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance_app', '0001_initial'),
        ('locations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets_app', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=100)),
                ('expiry_at', models.DateField(blank=True, null=True)),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Lô linh kiện',
                'verbose_name_plural': 'Lô linh kiện',
                'db_table': 'inventory_lots',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=300, verbose_name='Tên linh kiện')),
                ('uom', models.CharField(blank=True, max_length=20, verbose_name='Đơn vị tính')),
                ('is_lot_tracked', models.BooleanField(default=False)),
                ('is_expiry_tracked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Linh kiện/Vật tư',
                'verbose_name_plural': 'Linh kiện/Vật tư',
                'db_table': 'parts',
                'unique_together': {('tenant', 'part_code')},
            },
        ),
        migrations.CreateModel(
            name='PartIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_issues', to='assets_app.asset')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations_app.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_issues', to='maintenance_app.workorder')),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
                'db_table': 'part_issues',
            },
        ),
        migrations.CreateModel(
            name='PartIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_app.partissue')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.inventorylot')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.part')),
            ],
            options={
                'db_table': 'part_issue_items',
            },
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory_app.part'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations_app.location'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorylot',
            unique_together={('tenant', 'store_location', 'part', 'lot_no')},
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory_app.part')),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='locations_app.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'db_table': 'inventories',
                'unique_together': {('tenant', 'store_location', 'part')},
            },
        ),
        migrations.CreateModel(
            name='AssetAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=200, verbose_name='Tên phụ kiện')),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('OK', 'Bình thường'), ('MISSING', 'Thiếu'), ('DAMAGED', 'Hỏng')], default='OK', max_length=20)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='assets_app.asset')),
                ('last_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.part')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Phụ kiện thiết bị',
                'verbose_name_plural': 'Phụ kiện thiết bị',
                'db_table': 'asset_accessories',
                'indexes': [models.Index(fields=['tenant', 'asset'], name='asset_acces_tenant__8c4bac_idx')],
            },
        ),
    ]
